#!/bin/zsh

# Guard from multiple sourcing
if [[ -n "${ZSHRC_SOURCE_GUARD:-}" ]]; then
  return 0
fi
ZSHRC_SOURCE_GUARD=1


# ======== O S   D E T E C T I O N ========

if [ "$(uname)" = 'Darwin' ]; then
  OS='Mac'
elif [ "$(expr substr $(uname -s) 1 5)" = 'Linux' ]; then
  OS='Linux'
else
  echo "This computer OS: 'echo \$(uname)' = ${OS} is not recognized."
  exit 1
fi

# ======== P O W E R L E V E L   1 0 k ========

# Install powerlevel10k
# To configure, > p10k configure
export XDG_CACHE_HOME=$HOME/.cache/p10k
if [[ ! -d "$HOME/powerlevel10k" ]]; then
    echo "Installing powerlevel10k..."
    git clone -q --depth 1 https://github.com/romkatv/powerlevel10k.git $HOME/powerlevel10k
    $HOME/powerlevel10k/gitstatus/install
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# OS別のp10k設定をsource
DOTFILES_DIR="${0:A:h:h}"
if [ "$OS" = 'Mac' ]; then
    [[ -f "$DOTFILES_DIR/shell/p10k_mac.zsh" ]] && source "$DOTFILES_DIR/shell/p10k_mac.zsh"
else
    [[ -f "$DOTFILES_DIR/shell/p10k_ubuntu.zsh" ]] && source "$DOTFILES_DIR/shell/p10k_ubuntu.zsh"
fi

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# ======== A U T O   C O M P L E T E T I O N ========
autoload -U compinit
compinit
#setopt no_share_history

# Display cursor in completion
zstyle ':completion:*:processes' menu yes select=2
setopt magic_equal_subst

# setup kubectl completion
if type kubectl > /dev/null; then
  source <(kubectl completion zsh)
fi

# ======== C O L O R   F O R   L S ========
export LSCOLORS=exfxcxdxbxegedabagacad
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
zstyle ':completion:*' list-colors 'di=34' 'ln=35' 'so=32' 'ex=31' 'bd=46;34' 'cd=43;34'

alias ls="ls -GF"

# ======== M I S C ========


# Use nvim as a default
alias vim='nvim'

# history
HISTFILE=$HOME/.zsh-history
HISTSIZE=100000
SAVEHIST=1000000

# share .zshhistory
setopt inc_append_history
setopt share_history


# ======== F Z F ========
# Install fzf
if [ ! -d "$HOME/.fzf" ]; then
    git clone -q --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
    yes | $HOME/.fzf/install > /dev/null
fi
# Place zsh setup it not yet
if [ ! -f "$HOME/.fzf.zsh" ]; then
    yes | zsh -c "$HOME/.fzf/install"
fi
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# ======== ZSH AUTO SUGGESTION ========
# Install zsh-autosuggestions
mkdir -p $HOME/.zsh
if [ ! -f "$HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" ]; then
  git clone -q --depth 1 https://github.com/zsh-users/zsh-autosuggestions $HOME/.zsh/zsh-autosuggestions
fi
# Activate zsh-autosuggestions
if [ -f "$HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" ]; then
  source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
  bindkey '^[[Z' autosuggest-accept # Shift+Tab
fi


# ======== OS related configuration ========
if [ "$(uname)" = 'Darwin' ]; then
    # MacOS
    export LANG=en_US.UTF-8
    export LC_ALL=$LANG
    eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ "$(expr substr $(uname -s) 1 5)" = 'Linux' ]; then
    # Linux
    if [ -n $DISPLAY ]
    then
        xset r rate 200 50 &> /dev/null
    fi
fi

export PATH="$PATH:$HOME/.local/bin"


# ======== pyenv ========
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# ======== fnm (Fast Node Manager) ========
if [[ -d "$HOME/.local/share/fnm" ]]; then
    export PATH="$HOME/.local/share/fnm:$PATH"
    eval "$(fnm env --use-on-cd)"
fi

# ======== SSH Agent ========
if [ ! -d $HOME/.ssh ]; then mkdir $HOME/.ssh; fi
agent="$HOME/.ssh/agent"
if [ -S "$SSH_AUTH_SOCK" ]; then
    case $SSH_AUTH_SOCK in
    /tmp/*/agent.[0-9]*)
        ln -snf "$SSH_AUTH_SOCK" $agent && export SSH_AUTH_SOCK=$agent
    esac
elif [ -S $agent ]; then
    export SSH_AUTH_SOCK=$agent
fi

# ======== WezTerm SSH Tab Title ========
if [[ "$TERM_PROGRAM" == "WezTerm" ]]; then
  ssh() {
    # コマンドライン引数から -p オプションを探す
    local port_arg=""
    local i=1
    while [[ $i -le $# ]]; do
      local arg="${@[$i]}"
      if [[ "$arg" == "-p" ]]; then
        port_arg="${@[$((i+1))]}"
        break
      elif [[ "$arg" =~ ^-p(.+)$ ]]; then
        port_arg="${match[1]}"
        break
      fi
      ((i++))
    done

    # ssh -G でホスト名を取得
    local config=$(command ssh -G "$@" 2>/dev/null)
    local host=$(echo "$config" | awk '/^host / {print $2}')
    # .local サフィックスを削除
    host="${host%.local}"

    # コマンドラインで -p が指定された場合のみポートを表示
    local title="$host"
    [[ -n "$port_arg" ]] && title="$host:$port_arg"
    [[ -n "$host" ]] && printf '\033]1;🖥 %s\007' "$title"
    command ssh "$@"
    printf '\033]1;\007'
  }
fi

