version: "3.8"
services:
  dotfiles:
    build:
      args:
        - USER=$USER
        - GID=$G
        - UID=$U
        - PASSWORD=password
      context: .
    ports:
      - 2222:2222
    volumes:
      - ./docker/container-disk:/home/$USER/host-disk
      - .:/home/$USER/dotfiles
    privileged: true
    tty: true
