services:
  dotfiles:
    build:
      args:
        - USER=$USER
        - GID=$G
        - UID=$U
        - PASS=0000
        - UBUNTU_CODENAME=${UBUNTU_CODENAME:-jammy}
      context: .
    ports:
      - :${SSH_PORT:-2222}:2222
    volumes:
      - ./docker/.keys:/keys
      - ./docker/container-disk:/home/$USER/host-disk
      - .:/home/$USER/dotfiles
    privileged: true
    tty: true
