version: "3.8"
services:
  dotfiles:
    build:
      args:
        - USER=$USER
        - G=$GID
        - U=$UID
      context: .
    ports:
      - 2222:2222
    volumes:
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
      - ./docker/.keys:/keys
      - ./docker/disk:/home/$USER/host-disk
      - .:/home/$USER/dotfiles
    privileged: true
    tty: true
