version: "3.8"
services:
  dotfiles:
    build:
      args:
        - USER=$USER
        - GID=$GID
        - UID=$UID
      context: .
    ports:
      - 2222:2222
    volumes:
      - /etc/shadow:/etc/shadow:ro
      - .keys:/keys
    privileged: true
    tty: true
